// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApKouckMHhjhXc9rseJ58_T3GDrUDHdI',
    appId: '1:685074731446:web:def3a275060ebbea853117',
    messagingSenderId: '685074731446',
    projectId: 'qrapplication-bded6',
    authDomain: 'qrapplication-bded6.firebaseapp.com',
    storageBucket: 'qrapplication-bded6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDts2rT4kOykLoqG9HLbrbVJYZBLyXUov4',
    appId: '1:685074731446:android:2d2f63efafe169d6853117',
    messagingSenderId: '685074731446',
    projectId: 'qrapplication-bded6',
    storageBucket: 'qrapplication-bded6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMCSd9c7Oi43T5XJj2xQGW2eC1gj7mMLY',
    appId: '1:685074731446:ios:03e43e9d0b46d8cf853117',
    messagingSenderId: '685074731446',
    projectId: 'qrapplication-bded6',
    storageBucket: 'qrapplication-bded6.firebasestorage.app',
    iosBundleId: 'com.example.secureqrapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMCSd9c7Oi43T5XJj2xQGW2eC1gj7mMLY',
    appId: '1:685074731446:ios:03e43e9d0b46d8cf853117',
    messagingSenderId: '685074731446',
    projectId: 'qrapplication-bded6',
    storageBucket: 'qrapplication-bded6.firebasestorage.app',
    iosBundleId: 'com.example.secureqrapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAApKouckMHhjhXc9rseJ58_T3GDrUDHdI',
    appId: '1:685074731446:web:7bdf5e80ba75ccf9853117',
    messagingSenderId: '685074731446',
    projectId: 'qrapplication-bded6',
    authDomain: 'qrapplication-bded6.firebaseapp.com',
    storageBucket: 'qrapplication-bded6.firebasestorage.app',
  );
}
